---
title: "Prediction of age of abalone"
author: "Cassiel Huo "
date: '2019-12-05'
output: html_document
---

## Q1 Data analysis report

Simple Summarization of data set
```{r}
file1 <- "http://www.math.mcgill.ca/yyang/regression/data/abalone.csv"
abalone <- read.csv(file1, header = TRUE)
names(abalone)<-c('Height','Rings')
summary_var<-data.frame(Variance=var(abalone))
summary(abalone)
summary_var
```

Plot the individual histogram 1.The histogram of Height
```{r}
size<-nrow(abalone)-1
size
hist(abalone$Height, breaks = 75, main = "Histogram of Height", xlab="Height (mm)", ylab="Density", probability = TRUE,las=1)
densH <- density(abalone$Height,bw=0.01)
lines(smooth.spline(x = densH$x, y = densH$y), col = "orange", lwd = 2) 
box()
```

2. Then the graph of Rings
```{r}
hist(abalone$Rings, breaks=75, main="Histogram of Rings", axes=T, xlab="Rings",ylab="Density",probability = TRUE,las=1,xlim=c(0,29))
densR<-density(abalone$Rings, bw=1)
lines(smooth.spline(x=densR$x, y=densR$y), col="orange", lwd=2)
axis(side = 1, at = c(1,seq(5,25,5),29), labels = c(1,seq(5,25,5),29))
box()
```

Scatter Plot of Height VS Rings counted

```{r}
plot(abalone$Height, abalone$Rings, pch = 19, cex = 0.2, axes = TRUE, xlab="Height",ylab="Rings",las=1)
MODEL <- lm(abalone$Rings ~ abalone$Height)
abline(MODEL, col = "orange", lwd = 2)
meanX<-round(mean(abalone$Height),digits=2)
meanY<-round(mean(abalone$Rings),digits=2)
abline(v=meanX,h=meanY,lty=2)
axis(side=4,at=meanY,labels=as.character(meanY),las=1,font=5)
axis(side=1,at=meanX,labels=as.character(meanX),font=5)
```

plot the predictor against residuals 
```{r}
plot(MODEL,which=1)
```

fliter out outliers
```{r}

x<-abalone$Height
y<-abalone$Rings

newAbalone<-subset(abalone, x>0.04&x<0.24&y>3.5&y<15.5)
newX<-newAbalone$Height
newY<-newAbalone$Rings

plot(newX,newY, pch = 19, cex = 0.2, axes = TRUE, xlab="Height",ylab="Rings",las=1,main="Diagnostic Modeling")
newModel<-lm(newY~newX)
abline(newModel, col = "orange", lwd = 2)
newMeanX<-round(mean(newX),digits=2)
newMeanY<-round(mean(newY),digits=2)

abline(v=newMeanX,h=newMeanY,lty=2)
axis(side=4,at=newMeanY,labels=as.character(newMeanY),las=1,font=5)
axis(side=1,at=newMeanX,labels=as.character(newMeanX),font=5)

plot(newModel, which=1,cex=0.5,las=1)

```

residual distributions and Normal QQ plot
```{r}
par(mfrow=c(1,2))
hist(residuals(newModel), breaks = 40, freq = FALSE, xlab = "Residual ", main = "Residual distribution",las=1)
curve(dnorm(x, mean = 0, sd = sd(residuals(newModel))), add = TRUE, col = "orange")
box()
qqnorm(residuals(newModel),las=1)
qqline(residuals(newModel))
```

inference and result
```{r}
summary(newModel)
```

95% C.I. for intercept and slope
```{r}
confint(newModel, level=0.95)
mytable <- summary(newModel)$coefficients 
mytable
```

95% C.I. for h=0.128
```{r}
predata<- data.frame(newX=0.128)
predict(newModel, newdata = predata, interval = 'confidence',level=0.95)
```

99% C.I. for h=0.132
```{r}
predata2<-data.frame(newX=0.132)
predict(newModel, newdata = predata2, interval = 'confidence',level=0.99)
```


